// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"


import SetTrackerSubmitController from "./set_tracker_submit_controller"
application.register("set-tracker-submit", SetTrackerSubmitController)

import UpdateNotesController from "./update_notes_controller"
application.register("update-notes-submit", UpdateNotesController)
